# Generated by Django 4.0.6 on 2023-08-25 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0006_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batchs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desciption', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=100)),
                ('transactions', models.ManyToManyField(to='transactions.transaction')),
            ],
        ),
    ]
