# Generated by Django 4.0.6 on 2023-08-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchs',
            name='transactions',
        ),
        migrations.AddField(
            model_name='batchs',
            name='transactions',
            field=models.CharField(default='[]', max_length=50000000),
        ),
    ]
