# Generated by Django 4.0.6 on 2023-08-25 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_batchs_transactions_batchs_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchs',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='batchs',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
