# Generated by Django 4.0.6 on 2023-09-05 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_shedules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shedules',
            old_name='payment_method',
            new_name='payment_name',
        ),
        migrations.RemoveField(
            model_name='shedules',
            name='transaction_type',
        ),
    ]
