# Generated by Django 4.0.6 on 2023-10-28 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
