# Generated by Django 4.0.6 on 2023-10-28 00:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_delete_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP_Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('otp', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('attempt', models.IntegerField(default=0)),
            ],
        ),
    ]
