# Generated by Django 5.0.3 on 2024-03-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_otp_object_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp_object',
            name='token',
            field=models.CharField(default='', max_length=200),
        ),
    ]
