# Generated by Django 5.0.3 on 2024-03-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_otp_object_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp_object',
            name='reset_token',
            field=models.CharField(default='', max_length=200),
        ),
    ]
