# Generated by Django 5.0.3 on 2024-03-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_otp_object_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp_object',
            name='reset_token',
            field=models.CharField(default='hhhhhhh', max_length=200),
        ),
    ]
