# Generated by Django 5.0.3 on 2024-05-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoices_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
