# Generated by Django 5.0.3 on 2024-05-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='test',
            field=models.IntegerField(default=0),
        ),
    ]
