# Generated by Django 5.0.3 on 2024-05-19 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_product_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='test',
        ),
    ]
