# Generated by Django 4.0.6 on 2023-08-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_transaction_exp_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='Transaction_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default='12', max_length=5, verbose_name='Transaction_id'),
        ),
    ]
