# Generated by Django 4.0.6 on 2023-08-24 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_transaction_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
