# Generated by Django 5.0.3 on 2024-03-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_transactiondefaulttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantsFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('fee', models.IntegerField(default=10)),
            ],
        ),
    ]
