# Generated by Django 5.0.3 on 2024-03-14 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_merchantsfee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchantsfee',
            old_name='fee',
            new_name='fee_in_cent',
        ),
    ]
