# Generated by Django 5.0.3 on 2024-03-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_rename_fee_merchantsfee_fee_in_cent'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fee',
            field=models.FloatField(default=0),
        ),
    ]
