# Generated by Django 5.0.3 on 2024-03-14 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_transaction_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchantsfee',
            old_name='fee_in_cent',
            new_name='fee_in_percent',
        ),
    ]
