# Generated by Django 5.0.3 on 2024-03-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_rename_fee_in_cent_merchantsfee_fee_in_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantsfee',
            name='fee_in_percent',
            field=models.FloatField(default=10),
        ),
    ]
