# Generated by Django 5.0.3 on 2024-03-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_alter_merchantsfee_fee_in_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
