# Generated by Django 5.0.3 on 2024-03-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0020_transaction_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Default_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('page_default', models.CharField(default='/%2Faccount/dashboard2', max_length=200)),
            ],
        ),
    ]
