# Generated by Django 4.0.6 on 2023-09-04 10:51

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='bill_company',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='bill_first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='bill_last_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='bill_phone_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='recurring_schedule',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='customer',
            name='amount',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='card_number',
            field=models.CharField(default='', max_length=16, verbose_name='Card Number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.CharField(default='', max_length=100, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(default='', max_length=100, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='customer',
            name='cvv',
            field=models.CharField(default='', max_length=4, verbose_name='CVV'),
        ),
        migrations.AddField(
            model_name='customer',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='customer',
            name='exp_month',
            field=models.CharField(default='', max_length=5, verbose_name='Expiration Month'),
        ),
        migrations.AddField(
            model_name='customer',
            name='exp_year',
            field=models.CharField(default='', max_length=5, verbose_name='Expiration Year'),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_method',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='', max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(default='', max_length=100, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(default='Complete', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='transaction_type',
            field=models.CharField(default='', max_length=100, verbose_name='Transaction Type'),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(default='', max_length=10, verbose_name='Zip'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default=uuid.uuid1, max_length=150, verbose_name='Transaction_id'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='', max_length=100, verbose_name='Email'),
        ),
    ]
