# Generated by Django 4.0.6 on 2023-09-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_customer_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='status',
        ),
        migrations.AddField(
            model_name='customer',
            name='cards',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_method',
            field=models.CharField(default='', max_length=100),
        ),
    ]
