# Generated by Django 5.0.3 on 2024-03-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_remove_customer_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('first_name', models.BooleanField(default=True)),
                ('last_name', models.BooleanField(default=True)),
                ('company', models.BooleanField(default=True)),
                ('address', models.BooleanField(default=True)),
                ('city', models.BooleanField(default=True)),
                ('state', models.BooleanField(default=True)),
                ('zip_code', models.BooleanField(default=True)),
                ('country', models.BooleanField(default=True)),
                ('phone_number', models.BooleanField(default=True)),
                ('card_number', models.BooleanField(default=True)),
                ('exp_year', models.BooleanField(default=True)),
                ('exp_month', models.BooleanField(default=True)),
                ('cvv', models.BooleanField(default=True)),
                ('email', models.BooleanField(default=True)),
            ],
        ),
    ]
